### ISSUE TITLE
License

### ISSUE THREAD

**Issue by ndowens** [bbugyi200/bashlibs#1]
Can you upload a license to this, so I can include it in a package in VoidLinux

https://github.com/void-linux/void-packages/pull/7406

**Comment by bbugyi200** [comment]
I added an MIT license to this project. Let me know if anything else is needed.

**Comment by ndowens** [comment]
Can you tag a release?

**Comment by bbugyi200** [comment]
@ndowens I just released a new version (v0.2.0) of [cookie](https://github.com/bbugyi200/cookie) which includes the changes (new LICENSE file) to the bashlibs submodule. Will that work?

**Comment by ndowens** [comment]
> @ndowens I just released a new version (v0.2.0) of [cookie](https://github.com/bbugyi200/cookie). Will that work?

bashlibs needs a release tag so it can be packaged as well, thank you.

**Comment by bbugyi200** [comment]
@ndowens Got it. I just released the first version of bashlibs (v0.1.0).

Please let me know if anything else is needed.
